### ISSUE TITLE
Support Creation of Phasor Array Using Load from NumPy Array

### ISSUE THREAD

**Issue by engineerjoe440** [engineerjoe440/ElectricPy#115]
There's got to be a way to support this syntax:

```python
import numpy as np
import electricpy as ep
x = np.arrange(0, 720, 1)
v = ep.phasor(1, 178 + x)
```

Presently, there's an error:

```python-traceback
Traceback (most recent call last):
  File "<pyshell#27>", line 1, in <module>
    v = ep.phasor(1, 178 + x)
  File "C:\Python311\Lib\site-packages\electricpy\phasors.py", line 89, in phasor
    return _c.rect(mag, _np.radians(ang))
TypeError: only size-1 arrays can be converted to Python scalars
```

**Comment by marcostfermin** [comment]
You’re hitting this because phasor() currently calls cmath.rect(), which only accepts Python scalars. When ang is a NumPy array, cmath internally tries to coerce it to a float and throws “only size-1 arrays…”.

Fix: use NumPy’s vectorized trig to build the complex phasor instead of cmath.rect(). This supports:
- scalar mag/ang (returns a scalar complex like today)
- array ang (returns a NumPy complex array)
- array mag and/or ang with broadcasting

Proposed patch (phasors.py):

```
import numpy as np

def phasor(mag, ang=0):
    """
    Returns a complex phasor given magnitude and angle (degrees).

    Works with scalars and NumPy arrays (broadcasting supported).
    """
    # Convert to arrays for vector math (keeps Python scalars working too)
    mag_arr = np.asarray(mag)
    ang_arr = np.asarray(ang)

    theta = np.deg2rad(ang_arr)
    z = mag_arr * (np.cos(theta) + 1j*np.sin(theta))

    # Preserve prior behavior: if both inputs were scalar, return a Python complex
    if z.shape == ():
        return complex(z)
    return z
```

This keeps the public API identical but removes reliance on cmath.rect().
Also note: the example typo is np.arange, not np.arrange.

Minimal test:

```
import numpy as np
import electricpy as ep
x = np.arange(0, 720, 1)
v = ep.phasor(1, 178 + x)
assert v.shape == x.shape
assert np.iscomplexobj(v)
```

Also works:
```
ep.phasor([1,2,3], 30)  -> array([ ... ], dtype=complex)
ep.phasor(2, [0,90,180]) -> array([2+0j, 0+2j, -2+0j])
```
